---
- name: Build AMI
  hosts: imagebuilder
  tasks:
  - name: load secrets from ansible vault
    include_vars:
      file: "../vars/secrets.yml"
  - name: Build ami
    ansible.builtin.include_role:
      name: rprakashg.demos.build_ami
    vars:
      blueprint_name: "rhde"